---
title: "News"
author: "Troy Hall, Sam Galloway, Rees Braam, Sidh Kulgod"
date: "Aproil 8, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, warning=FALSE}
set.seed(1337)
library(tidyverse)
library(dplyr)
library(readr)
```

```{r, cache=TRUE, message=FALSE, warning=FALSE}
# Read the datasets we specified

# Online News Popularity from https://archive.ics.uci.edu/ml/datasets/Online+News+Popularity
OnlineNewsPopularity <- rbind(read_csv("data/OnlineNewsPopularity/OnlineNewsPopularityTraining.csv"), read_csv("data/OnlineNewsPopularity/OnlineNewsPopularityTest.csv"))

# All the news from https://www.kaggle.com/snapcrack/all-the-news
AllTheNews <- read_csv("data/all-the-news/all-the-news.csv")

# All the news from https://www.kaggle.com/uciml/news-aggregator-dataset
NewsAggregatorDataset <- read_csv("data/news-aggregator-dataset.csv")
```

```{r}
head(OnlineNewsPopularity)

head(AllTheNews)

head(NewsAggregatorDataset)
```

```{r}
colnames(OnlineNewsPopularity)
```
```{r}
AllTheNews <- AllTheNews %>% select(1:month, day, day_of_week, url:polarity) # Switches order of columns
colnames(AllTheNews)
```

```{r}
colnames(NewsAggregatorDataset)
```

### Filter the rows in *OnlineNewsPopularity* where there was an error getting the text.
```{r}
# Remove the 22 NA rows from OnlineNewsPopularity

sum(is.na(OnlineNewsPopularity$text) == TRUE)
OnlineNewsPopularity <- filter(OnlineNewsPopularity, is.na(OnlineNewsPopularity$text) == FALSE)
sum(is.na(OnlineNewsPopularity$text) == TRUE)
```

### Filter out the rows where date had an issue being parsed, maybe fixable at a later date
```{r}
nrow(filter(AllTheNews, AllTheNews$day_of_week == -1))
AllTheNews <- filter(AllTheNews, AllTheNews$day_of_week != -1)
nrow(filter(AllTheNews, AllTheNews$day_of_week == -1))
```
### Make changes to OnlineNewsPopularity to prepare it to be combined with the others
```{r}
OnlineNewsPopularity$day_of_week = 0 * OnlineNewsPopularity$weekday_is_monday + 1 * OnlineNewsPopularity$weekday_is_tuesday + 2 * OnlineNewsPopularity$weekday_is_wednesday + 3 * OnlineNewsPopularity$weekday_is_thursday + 4 * OnlineNewsPopularity$weekday_is_friday + 5 * OnlineNewsPopularity$weekday_is_saturday + 6 * OnlineNewsPopularity$weekday_is_sunday
```

